# Generated by Django 4.2.7 on 2024-03-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
