# Generated by Django 4.2.7 on 2024-03-20 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_quizsubmit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant_Care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('W', 'Watered'), ('F', 'Fertilized'), ('P', 'Pruned'), ('R', 'Repotted'), ('PC', 'Pest Control')], default='W', max_length=2)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.plant')),
            ],
        ),
    ]
